//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPortfolio.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MyportfolioEntities1 : DbContext
    {
        public MyportfolioEntities1()
            : base("name=MyportfolioEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Tbl_Abouts> Tbl_Abouts { get; set; }
        public virtual DbSet<Tbl_Categories> Tbl_Categories { get; set; }
        public virtual DbSet<Tbl_Contacts> Tbl_Contacts { get; set; }
        public virtual DbSet<Tbl_Exp> Tbl_Exp { get; set; }
        public virtual DbSet<Tbl_Features> Tbl_Features { get; set; }
        public virtual DbSet<Tbl_Messages> Tbl_Messages { get; set; }
        public virtual DbSet<Tbl_Projects> Tbl_Projects { get; set; }
        public virtual DbSet<Tbl_Services> Tbl_Services { get; set; }
        public virtual DbSet<Tbl_Skills> Tbl_Skills { get; set; }
        public virtual DbSet<Tbl_SocialMedias> Tbl_SocialMedias { get; set; }
        public virtual DbSet<Tbl_Teams> Tbl_Teams { get; set; }
        public virtual DbSet<Tbl_Testimonials> Tbl_Testimonials { get; set; }
        public virtual DbSet<Tbl_Admin> Tbl_Admin { get; set; }
    }
}
